import Head from 'next/head'
import Image from 'next/image'

import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { typeProduct } from '@/@types'
import HeroBannner from '@/components/HeroBannner'
import Product from '@/components/Product'
import FooterBanner from '@/components/FooterBanner'



interface Props{
  products: typeProduct[];
  error:string;
}
export default function Home({products, error}:Props) {
  console.log('hello')

 console.log(process.env.baseURL)
  return (
    <>
      <Head>
        <title>Next Js Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
      <HeroBannner/>
      <div className="products-heading">
      <h2>Design Your Comfort</h2>
      <p>Transform your space with our premium selection of furniture</p>
    </div>
  
    <div className="products-container">
      
  {products?.length > 1 ? (
    products.map((product) => <Product key={product._id} product={product} />)
  ) :(<h1>Loading...</h1>)}
</div>


      <FooterBanner/>
      </div>

    </>
  )

  
}

export const getServerSideProps = async () => {
  try {
    const { data } = await axios.get('http://localhost:4000/api/v1/products');
    const products = data.products.slice(0, 8);
    return {
      props: { products },
    };
  } catch (error) {
    return {
      props: { error: 'Failed to fetch products' },
    };
  }
};
